import { Capacitor } from '@capacitor/core';
import type { CallbackID } from '@capacitor/geolocation';
import type { GpsPosition } from '@/models';

function toGpsPosition(position:{coords:{latitude:number;longitude:number;accuracy:number;altitude:number|null};timestamp:number}):GpsPosition{return {latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy,altitude:position.coords.altitude??undefined,timestamp:position.timestamp}}
export const gpsService={
 async getCurrentPosition():Promise<GpsPosition>{if(Capacitor.isNativePlatform()){const {Geolocation}=await import('@capacitor/geolocation');const permission=await Geolocation.requestPermissions();if(permission.location==='denied')throw new Error('Permiso de ubicación denegado');return toGpsPosition(await Geolocation.getCurrentPosition({enableHighAccuracy:true,timeout:15000,maximumAge:0}))}return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(new Error('GPS no disponible'));return}navigator.geolocation.getCurrentPosition(p=>resolve(toGpsPosition(p)),e=>reject(new Error(e.message)),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})},
 watch(onPosition:(p:GpsPosition)=>void,onError:(message:string)=>void){if(Capacitor.isNativePlatform()){let active=true;let watchId:CallbackID|undefined;void import('@capacitor/geolocation').then(async({Geolocation})=>{const permission=await Geolocation.requestPermissions();if(!active)return;if(permission.location==='denied'){onError('Permiso de ubicación denegado');return}watchId=await Geolocation.watchPosition({enableHighAccuracy:true,maximumAge:2000,timeout:20000},(position,error)=>{if(error){onError(error.message);return}if(position)onPosition(toGpsPosition(position))})}).catch((error:unknown)=>onError(error instanceof Error?error.message:'GPS no disponible'));return()=>{active=false;if(watchId!==undefined)void import('@capacitor/geolocation').then(({Geolocation})=>Geolocation.clearWatch({id:watchId}))}}if(!navigator.geolocation){onError('GPS no disponible');return ()=>{}}const id=navigator.geolocation.watchPosition(p=>onPosition(toGpsPosition(p)),e=>onError(e.message),{enableHighAccuracy:true,maximumAge:2000,timeout:20000});return()=>navigator.geolocation.clearWatch(id)}
};
export function distanceMeters(a:{latitude:number;longitude:number},b:{latitude:number;longitude:number}){const r=6371e3,p1=a.latitude*Math.PI/180,p2=b.latitude*Math.PI/180,dp=(b.latitude-a.latitude)*Math.PI/180,dl=(b.longitude-a.longitude)*Math.PI/180; const h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return 2*r*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
