import { useEffect,useRef,useState } from 'react'; import type { GpsPosition,Valve } from '@/models'; import { mapService } from '@/services/mapService';

const OFFLINE_STYLE: import('maplibre-gl').StyleSpecification={version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#e5edf2'}}]};

export function MapView({valves,position,onSelect}:{valves:Valve[];position:GpsPosition|null;onSelect:(v:Valve)=>void}){
 const container=useRef<HTMLDivElement>(null),mapRef=useRef<import('maplibre-gl').Map|null>(null),valvesRef=useRef(valves),selectRef=useRef(onSelect),[error,setError]=useState<string|null>(null);
 valvesRef.current=valves;selectRef.current=onSelect;
 useEffect(()=>{if(!container.current||mapRef.current)return;let active=true;import('maplibre-gl').then(({default:maplibregl})=>{if(!active||!container.current)return;const first=valvesRef.current[0];const map=new maplibregl.Map({container:container.current,style:OFFLINE_STYLE,center:first?[first.longitud,first.latitud]:[-77.05,-12.04],zoom:13,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.on('error',event=>setError(event.error?.message??'No se pudo dibujar el mapa.'));map.on('load',()=>{map.addSource('valves',{type:'geojson',data:mapService.toFeatureCollection(valvesRef.current)});map.addLayer({id:'valves',type:'circle',source:'valves',paint:{'circle-radius':9,'circle-color':'#1685b8','circle-stroke-color':'#ffffff','circle-stroke-width':3}});map.on('click','valves',(event:import('maplibre-gl').MapMouseEvent & {features?:import('maplibre-gl').MapGeoJSONFeature[]})=>{const id=event.features?.[0]?.properties?.['id'];const valve=valvesRef.current.find(item=>item.id===id);if(valve)selectRef.current(valve)});map.on('mouseenter','valves',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','valves',()=>map.getCanvas().style.cursor='')});mapRef.current=map;requestAnimationFrame(()=>map.resize())}).catch(()=>setError('No se pudo iniciar el visor cartográfico.'));return()=>{active=false;mapRef.current?.remove();mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;const update=()=>{const source=map.getSource('valves') as import('maplibre-gl').GeoJSONSource|undefined;source?.setData(mapService.toFeatureCollection(valves));if(valves.length){const bounds=new MapLibreBounds(valves);map.fitBounds(bounds,{padding:80,maxZoom:15,duration:0})}};map.isStyleLoaded()?update():map.once('load',update)},[valves]);
 useEffect(()=>{const map=mapRef.current;if(!map||!position)return;const add=()=>{const point={type:'Point' as const,coordinates:[position.longitude,position.latitude]};const source=map.getSource('user') as import('maplibre-gl').GeoJSONSource|undefined;if(source){source.setData(point);return}map.addSource('user',{type:'geojson',data:point});map.addLayer({id:'user',type:'circle',source:'user',paint:{'circle-radius':9,'circle-color':'#dc2626','circle-stroke-color':'#ffffff','circle-stroke-width':4}})};map.isStyleLoaded()?add():map.once('load',add)},[position]);
 return <div className="relative h-full min-h-[460px] w-full"><div ref={container} className="absolute inset-0" aria-label="Mapa de válvulas"/>{error&&<div className="absolute inset-x-4 top-20 z-20 rounded-md bg-destructive-soft p-3 text-sm text-destructive">{error}</div>}</div>
}

class MapLibreBounds{
 private west:number;private south:number;private east:number;private north:number;
 constructor(valves:Valve[]){const first=valves[0];this.west=first?.longitud??-77.05;this.east=this.west;this.south=first?.latitud??-12.04;this.north=this.south;for(const valve of valves){this.west=Math.min(this.west,valve.longitud);this.east=Math.max(this.east,valve.longitud);this.south=Math.min(this.south,valve.latitud);this.north=Math.max(this.north,valve.latitud)}}
 toArray():[[number,number],[number,number]]{return [[this.west,this.south],[this.east,this.north]]}
}
